const { SlashCommandBuilder } = require('@discordjs/builders');

var gifs = [
    "https://c.tenor.com/ifTL4Pv2aIIAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/CwSzsSZjHWoAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/sXdi-uqp0DYAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/pnTGmxiSg-8AAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/-HQfyR8RLTwAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/Dg6Z5-6TnVcAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/1Pvs5mUvYl0AAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/nvoNxBIzoHYAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/QqIKPodiPsUAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/FRQVbnaePVoAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/a_0o2jqf7mQAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/Am_q0a3qim4AAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/Y0_X9fiZ3aIAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/4Cl88wyj3nMAAAAC/fluf-world-partybear.gif",
    "https://c.tenor.com/G_kYgdP_4DwAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/R043IGj7-PsAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/MxPzPaVGDlEAAAAC/pew-pew-pew-fluf-world.gif",
    "https://c.tenor.com/xIZUww7VPAcAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/uW54IjiESd0AAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/Q0ip7myUFmoAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/0rV7pdxKjEAAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/txH-gPQoMTQAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/7pFbQNzy-hwAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/k45Aoq6NxoMAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/HtcZ0b20KHwAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/nfQbphqg5CQAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/i2ApSsoza9IAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/h4lqGWmKIWIAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/KeAZPrNEfgEAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/e5xJntWs-8gAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/YS8UEPwWJxkAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/kU0KDiqhUWwAAAAd/fluf-this-is-the-way.gif",
    "https://c.tenor.com/CW8ewK4FPagAAAAd/fluf.gif",
    "https://c.tenor.com/E_DFsadGG90AAAAd/fluf-its-about-sending-a-message.gif",
    "https://c.tenor.com/JT3imTuB3TEAAAAd/fluf-thingies.gif",
    "https://c.tenor.com/0qfzI7RYr_QAAAAC/fluf-this.gif",
    "https://c.tenor.com/jPWSxSaYaKgAAAAC/alpha-alert-flufworld.gif",
    "https://c.tenor.com/LuvpzkbBQjMAAAAC/fluf-love.gif",
    "https://c.tenor.com/04SXFi9gAJcAAAAd/fluf-dance.gif",
    "https://c.tenor.com/A4-5zm3m_zUAAAAC/flufworld-fluf.gif",
    "https://c.tenor.com/9WRXeMH8ulkAAAAC/flufworld-fluf.gif",
    "https://c.tenor.com/FVvzcIQksPwAAAAC/limi-limicent.gif",
    "https://c.tenor.com/CusaEBZqPfYAAAAC/limicent-limi.gif",
    "https://c.tenor.com/jabOURla4QoAAAAd/gm-fluffle-limicent.gif",
    "https://c.tenor.com/BdiSigK2ysgAAAAC/fluf-pew-pew-pew.gif",
    "https://c.tenor.com/Os76qEzhR94AAAAC/show-me-the-honey-partybear.gif",
    "https://c.tenor.com/JTWIbplyNk0AAAAC/aaron-mcd-flufworld.gif",
    "https://c.tenor.com/hexeq9ASP70AAAAC/atem-limi.gif",
    "https://c.tenor.com/KFKFXSt_47EAAAAC/fluf-flufworld.gif",
    "https://c.tenor.com/FR86m7Uyyg8AAAAd/fluf-harley-fluf.gif",
    "https://c.tenor.com/-xxHylSNZEoAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/ktWlvnpflMMAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/pdcp3YEthHkAAAAC/shut-up-and-take-my-money-shut-up-and-take-my-carrots.gif",
    "https://c.tenor.com/Hi0v_YEx5bMAAAAC/literally-shaking-fluf.gif",
    "https://c.tenor.com/vodF9FnY9hQAAAAC/fluf-flufworld.gif",
    "https://c.tenor.com/A3J1PKeiKqYAAAAC/fluf-world.gif",
    "https://c.tenor.com/obmXFNWIzzcAAAAC/fluf-world-party-bears.gif",
    "https://c.tenor.com/V30vGyaKuOkAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/dX0qsAw1QUQAAAAC/fluf-world-angelbaby.gif",
    "https://c.tenor.com/cPh9UxgQ6dUAAAAC/fluf-world.gif",
    "https://c.tenor.com/xGJTYtjitP8AAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/xWxNAB2EstwAAAAM/fluf-world-fluf.gif",
    "https://c.tenor.com/5r1ceFuNVJwAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/YK1RxaPyz_EAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/zny0VS4qL4oAAAAC/fluf-world-party-bear.gif",
    "https://c.tenor.com/SA34busdvTcAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/sgRM0UtxxIQAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/OoS5I9AiiwEAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/h8YspqLanEoAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/UOyX39_QZdkAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/aD4hCCHAu_wAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/AO7JXu7enEgAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/RETppGhDmb0AAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/dW-LFHLQHpcAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/mrgkHN3s9dcAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/_8Rc6Sfb5BoAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/vxScTbj0Qy4AAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/BKtTNbyPG-0AAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/nweie-3t6AIAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/bT54LXhY8SEAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/22M-YcaWAsgAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/rBAOt-8v95AAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/xN_wODA_y1sAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/L1RbxexvSdAAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/fhVrj2kW5IwAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/tDenZG_svM0AAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/ySAdRWzOxTkAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/QcTvVQFRDg4AAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/cxy5ZsZx1uAAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/8VO2b65p8m0AAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/xRci5k0BJZkAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/QRAhYx6HG5MAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/M_uG9XOFz3cAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/wr2v9EoUb4cAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/5zbBxepwAGEAAAAd/fluf-world-fluffy-cat.gif",
    "https://c.tenor.com/T3H86Hc-_dkAAAAd/fluf-world-fluf.gif",
    "https://c.tenor.com/9_J5FYlZH0gAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/9YVX_u_QOzsAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/CmGoqP8ZHbcAAAAC/fluf-world-fluf.gif",
    "https://c.tenor.com/PgFeb-r0PMAAAAAd/literally-shaking-shaking.gif",
    "https://c.tenor.com/4na1IXRuKskAAAAd/30min-max-fluf.gif",
    "https://c.tenor.com/hsGzzy8EJogAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/9hVzRMjv1UQAAAAd/fluf-delist.gif",
    "https://c.tenor.com/ujNz4vX_THIAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/XjGIoF_e6REAAAAC/30min-max-fluf-world.gif",
    "https://c.tenor.com/AvMApMJQXWUAAAAC/fluf-yeah-fluf-yeah-dance.gif",
    "https://c.tenor.com/jRoYj2dUrSQAAAAd/shaking-literally-shaking.gif",
    "https://c.tenor.com/yGXYtfOUbGUAAAAC/fluf-fluf-world.gif",
    "https://c.tenor.com/H6OAWE_9OEMAAAAC/fluf-flufward.gif",
    "https://c.tenor.com/9Af4g4X9enkAAAAd/fluf-fluf-world.gif",
    "https://c.tenor.com/QnPx9XgNh9UAAAAC/party-bear-fluf.gif",
    "https://c.tenor.com/iONtp5NM3E8AAAAd/snoop-snoop-dogg.gif",
    "https://c.tenor.com/5aJgVSTpYMUAAAAd/literally-shaking-fluf-world.gif",
    "https://c.tenor.com/K1NKE5TbybkAAAAC/fluf-fluf-world.gif"

  ];
  
  function selectGif(){
    let randGif = Math.floor(Math.random() * (gifs.length));
    return gifs[randGif];
  }


module.exports = {
	data: new SlashCommandBuilder()
		.setName('flufworldgif')
		.setDescription('Replies with a random gif from Fluf World ecosystem!'),
	async execute(interaction) {
    let randomGif = selectGif();
		await interaction.reply(randomGif);
	},
};